### PR TITLE
fix show for adjoint/transpose of CSC matrices.

### LINKED ISSUE #210: Cannot show adjoint of sparse matrix
This fails
```Julia
using SparseArrays
@show sparse([1 2; 3 4])'
```
with the error
```
ERROR: MethodError: no method matching rowvals(::Adjoint{Int64, SparseMatrixCSC{Int64, Int64}})
```

I am using
```
julia> versioninfo()
Julia Version 1.8.0-rc3
Commit 33f19bcbd25 (2022-07-13 19:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 16 virtual cores
```

### PR DESCRIPTION
**Pull request by SobhanMP**
also make it non-allocating.
closes #210

### CODE REVIEW

**Comment by SobhanMP** [comment]
gonna need some opinions, is `transpose(sparse([1, 2, 1, 2], [1, 1, 2, 2], [1, 3, 2, 4], 2, 2))` a good way of showing it?

**Comment by eschnett** [comment]
That sounds good.

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
It would be good for the test to use a 2x3 matrix...

**Comment by ViralBShah** [comment]
Does this do the same thing as dense? Sorry for these comments after approving. Late thoughts.

**Comment by eschnett** [comment]
No, dense matrices are shown transposed. This doesn't work for sparse matrices, because for sparse matrices we show the internal structure. Transposing this would be a `SparseMatrixCSR` (compressed sparse row), and since the difference between `...CSC` and `...CSR` is difficult to see, wrapping the output in `adjoint(...)` makes sense.

Maybe we shouldn't show the internal structure of the matrix, but instead list the nonzero elements? That would be much easier to understand, and would be straightforward to transpose.

**Comment by ViralBShah** [comment]
Yes, that is what I was thinking - that we should just focus on showing the nonzero elements instead of the internal structure.

**Comment by SobhanMP** [comment]
since it's in COO, `adjoint(sparse(I, J, V)) = sparse(J, I, V)` right?

**Comment by ViralBShah** [comment]
Yes, that is right for COO adjoint.

**Comment by SobhanMP** [comment]
so do i write the actual adjoint (in COO) or do we keep it as is?

**Comment by ViralBShah** [comment]
IIUC, the dense case does show the actual adjoint.

**Comment by eschnett** [comment]
Actually, I am annoyed by the current `@show` output for sparse arrays. The CSC format is not human-readable at all, and that output is always useless for me. I always have to use `display` or another mechanism to look at sparse arrays. I would very much prefer if all `@show` output for sparse array just listed the non-zero elements (i.e. outputs the COO format). That's also what the constructor expects.

**Comment by eschnett** [comment]
... and `@show` for a `Diagonal` matrix shows it as full matrix, not even indicating that it is stored as `Diagonal`?

**Pull request merged**
