### PR TITLE
Backports to v1.10

### PR DESCRIPTION
**Pull request by dkarrasch**

### CODE REVIEW

**Comment by dkarrasch** [comment]
Do we have more to add here? Otherwise, we should merge this and then bump it into https://github.com/JuliaLang/julia/pull/56381.

**Comment by ViralBShah** [comment]
I think we want #560

**Comment by ViralBShah** [comment]
Should we update the CI on this branch to run on 1.10?

**Comment by dkarrasch** [comment]
Oh, I forgot about our label, so there's a lot marked for backport, actually. I'll go through the list. CI seems to be running on v1.10?

I can't backport #550. It has quite some heavy merge conflicts that I don't know how to resolve.

**Comment by dkarrasch** [comment]
> There are several others marked as backport to 1.10, but many probably have already been backported. Perhaps we should remove the labels?

I have cleaned up the list. Everything (up to #550) is included and I removed the labels.

**Comment by ViralBShah** [comment]
> I have cleaned up the list. Everything (up to #550) is included and I removed the labels.

Thank you!

**Comment by ViralBShah** [comment]
I isolated the commit for disabling nested dissection and pushed it. Unfortunately, instead of a branch I pushed directly to release-1.10. Also updated the CI. I might need to push a few more to make sure it all ends up working out.

**Comment by ViralBShah** [comment]
Would it be ok to remove those commits and force push on the 1.10 branch? I am creating a new PR against the `backports-release-1.10` branch.

**Comment by ViralBShah** [comment]
cc @KristofferC

**Comment by ViralBShah** [comment]
Verified that the issue reported in #548 is fixed on this branch.

**Comment by dkarrasch** [comment]
This seems like done. I'm merging this.

**Pull request merged**
