### PR TITLE
add faster sum/any/all/iszero

### PR DESCRIPTION
**Pull request by SobhanMP**
closes https://github.com/JuliaSparse/SparseArrays.jl/issues/237
i'll write tests tomorrow

would it make sense that the functions for transpose/adjoint be added to LinearAlgebra.jl?

can nonzeros be larger than nnz? there are code where it would be valid and code that it would not be.

### CODE REVIEW

**Comment by dkarrasch** [comment]
But LinearAlgebra doesn't know about `SparseXYZ`. I think these functions should live here. I remember we have made an effort to implement efficient reduction functions. Don't they apply here? Maybe there is some dispatch going in the wrong direction? Looking at sparsevector.jl lines 1425ff, there is sparsity-aware code.

**Comment by dkarrasch** [comment]
Wait. This doesn't apply to `SparseVector`s, but to sparse matrices? But then again, we have code in sparsematrix.jl lines 2132ff, and seemingly a specialization for `+`.

**Review by dkarrasch — CHANGES_REQUESTED** [review]
I believe this is all actually handled well, see my comment in the original issue. What is missing is a `count` specialization for `Bool` sparse arrays.

**Comment by SobhanMP** [comment]
> But LinearAlgebra doesn't know about SparseXYZ. 

sure but what ever the parent is, shouldn't Transpose just forward it to the parent? like always

**Comment by dkarrasch** [comment]
I see what you mean. Like

```julia
iszero(x::AdjOrTrans) = iszero(parent(x))
```

right?

**Comment by SobhanMP** [comment]
yeah

**Comment by SobhanMP** [comment]
closed in favor #244

**Pull request closed without merging**
