### PR TITLE
Make lu! reuse working buffers

### PR DESCRIPTION
**Pull request by SobhanMP**
had to close https://github.com/JuliaSparse/SparseArrays.jl/pull/104 due to ... issues with git.

### CODE REVIEW

**Comment by SobhanMP** [comment]
@ViralBShah is there any reason to not merge this and the qsymbolic patch atm? (after CI of-course) both are non-breaking

**Comment by ViralBShah** [comment]
Yes, let's merge. I'll let you go about the merging to minimize conflicts if there are.

**Comment by SobhanMP** [comment]
i think this should go first but i think there are a bunch of conflicts..i'll fix them after you merged this one.

**Comment by ViralBShah** [comment]
I thought I had given you write access - Seems like I still haven't understood the latest iteration of github permissioning. Anyways, added you now - you should be able to merge.

**Pull request merged**
