### PR TITLE
Fix `vcat` of sparse vectors with numbers

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes the `vcat` aspect of #251.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I'm not sure how backports will work. @DilumAluthge @KristofferC ?

**Comment by DilumAluthge** [comment]
The high-level process is described in https://github.com/JuliaSparse/SparseArrays.jl/issues/249

**Comment by dkarrasch** [comment]
Ok, shall we merge this and then cherry-pick the commit and PR into `backports-release-1.8`? From there, we should PR into `release-1.8` and declare that in Julia, right?

**Comment by ViralBShah** [comment]
Sounds about right. Please merge when you are ready.

**Comment by dkarrasch** [comment]
Let's see what the backport github action does once I merge...

**Pull request merged**
