### PR TITLE
add undef initializers

### PR DESCRIPTION
**Pull request by matbesancon**
This is useful to have a unified way to create sparse and dense vectors.

Will add tests if the feature is considered useful / needed

### CODE REVIEW

**Comment by Wimmerer** [comment]
Is this semantically correct compared to other undef initializers? If so this seems like a fine addition.

**Comment by matbesancon** [comment]
> Is this semantically correct compared to other undef initializers

it seems so, the type has to be given as type parameter, it creates a new object of the same type

**Comment by Wimmerer** [comment]
I'll approve with a few tests and maybe a short docstring to clarify that this is an empty spmatrix.

**Comment by matbesancon** [comment]
done

**Pull request merged**
