### PR TITLE
replace ind2sub/sub2ind by CartesianIndices/LinearIndices

### PR DESCRIPTION
**Pull request by jishnub**
This avoids using the internal `Base` methods

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
Is there any perf impact?

**Comment by jishnub** [comment]
There does appear to be a small performance impact.
```julia
julia> S = sparse([1:500;], [x + (isodd(x) ? 1 : -1) for x in 1:500], [1:500;]);

julia> @btime $S[1:100_000];
  1.439 μs (2 allocations: 8.12 KiB) # master
  1.531 μs (2 allocations: 8.12 KiB)
```
In this case, the difference appears to arise from indexing into the `LinearIndices`. I'm unsure why this indexing is slower, as it calls `_sub2ind` internally, and bounds-checking is disabled.

**Comment by ViralBShah** [comment]
I wonder what the speed impact would be on larger operations. It is a 7% slowdown in the benchmark, which may perhaps manifest as 1-2% slowdown on larger operations or applications.

**Comment by vtjnash** [comment]
I seem to get the same code for these, so maybe that was just a benchmarking artifact of some runs?
```
julia> LinearIndices(Matrix{Int}(undef,0,0)) |> typeof
julia> code_native((ans, Int, Int)) do x, y, z; @inbounds x[y, z]; end
julia> code_native((Tuple{Int,Int}, Int, Int)) do x, y, z; @inbounds Base._sub2ind(x, y, z); end
```
Seems like this should be good to merge to me

**Pull request merged**
