### PR TITLE
Adapt to Documenter v1

### PR DESCRIPTION
**Pull request by dkarrasch**
Let's see if we need to exclude parts of the docs from the now default strict behavior.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@mortenpi Is there a way to cross-reference docstrings from `LinearAlgebra` and `Base` (methods)? Is there a way to cross-reference to the "Random Numbers" section somewhere in the `Base` documentation? Perhaps an URL would work. But is that stable against new releases etc?

**Comment by mortenpi** [comment]
Nope, and that's non-trivial: https://github.com/JuliaDocs/Documenter.jl/issues/688

**Comment by dkarrasch** [comment]
Thank you very much for the quick response. Then I went in the right direction removing these references, many of which were somewhat overambitious (like `Float64`).

**Comment by ViralBShah** [comment]
I would defer to @mortenpi - since I am not familiar with the Documenter 1.0 changes yet. The docs do build, and the PR does look ok.

**Comment by mortenpi** [comment]
Oh.. so this is a standard library, right? Those links do work when it gets built as part of the Julia manual: https://docs.julialang.org/en/v1/stdlib/SparseArrays/ So I think it would be better to leave them in for now?

**Comment by mortenpi** [comment]
I don't think there's an easy workaround here. I think the best thing we can do is to make them warnings here by adding `:cross_references` to `warnonly`. But some bad link then may still break the combined manual build.

**Comment by ViralBShah** [comment]
I think that would be fine. At least it would allow us to catch more egregious problems sooner. Links are relatively easy to fix.

**Review by ViralBShah — APPROVED** [review]

**Comment by matbesancon** [comment]
good to go?

**Review by matbesancon — APPROVED** [review]

**Pull request merged**
