### PR TITLE
Update the wrappers for SuiteSparse 7

### PR DESCRIPTION
**Pull request by ViralBShah**
Try to update the SuiteSparse wrappers for SuiteSparse 7 using Julia master.

cc @fxcoudert

### CODE REVIEW

**Comment by ViralBShah** [comment]
@Gnimuc Would the generator.jl file for generating the SuiteSparse wrappers need to be updated for the new Clang.jl? The script runs through with Julia master, but in the generated files, there are various C constants like `int64_t`, `LONG_MAX`, `__STDC_VERSION__` etc.

Help appreciated.

**Comment by Gnimuc** [comment]
Please do not bump Clang.jl's minor version and the C lib's major version simultaneously. It's hard to figure out what causes the changes in the generated result.

**Comment by Gnimuc** [comment]
@Wimmerer does SuiteSparse 7 introduce breaking changes? I mean we may need to upgrade those high-level wrappers as well.

**Comment by Wimmerer** [comment]
Very possibly. I need to examine what we do with SuiteSparse_config

**Comment by Wimmerer** [comment]
I will try to do that tonight

**Comment by ViralBShah** [comment]
I believe @fxcoudert implement that change relating to the API change with the config strict in one of the recent PRs to this package.

There may be other changes.

**Comment by ViralBShah** [comment]
> Please do not bump Clang.jl's minor version and the C lib's major version simultaneously. It's hard to figure out what causes the changes in the generated result.

Makes sense. I wasn't sure how to do this. We should close this PR.

**Comment by Gnimuc** [comment]
I tested the generator locally. The generated results have no changes after bumping Clang.jl from v0.15 to v0.17.

**Comment by Gnimuc** [comment]
But I failed to upgrade `SuiteSparse_jll` to v7.0.1:

```
(gen) pkg> add SuiteSparse_jll@v7.0.1
   Resolving package versions...
  No Changes to `~/.julia/dev/SparseArrays.jl/gen/Project.toml`
  No Changes to `~/.julia/dev/SparseArrays.jl/gen/Manifest.toml`

(gen) pkg> st
Status `~/.julia/dev/SparseArrays.jl/gen/Project.toml`
  [40e3b903] Clang v0.17.3
  [bea87d4a] SuiteSparse_jll v5.10.1+6
```

**Comment by ViralBShah** [comment]
Yes, because it is an stdlib, it gets pinned. I find it easiest to disable it in the system image and then bump the version on Julia master. I have a local copy that I can provide as a branch.

**Comment by ViralBShah** [comment]
@Gnimuc I have prepared https://github.com/JuliaLang/julia/pull/48977, which should make it easy to update these wrappers.

**Pull request closed without merging**
