### PR TITLE
CI: Add Apple Silicon (macOS aarch64) to the CI matrix

### PR DESCRIPTION
**Pull request by ViralBShah**
GitHub Actions now offers free Apple Silicon macOS runners for public repositories:

> Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`.

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

https://discourse.julialang.org/t/github-actions-now-offers-free-apple-silicon-macos-runners-for-public-repositories/109641

### CODE REVIEW

**Comment by ViralBShah** [comment]
@DilumAluthge Do you know how to enable apple silicon support? Apparently the path being constructed is incorrect.

**Comment by DilumAluthge** [comment]
Okay, so this is what I see:

```
Run julia-actions/setup-julia@v1
  with:
    version: nightly
    arch: ARM64
    include-all-prereleases: false
    show-versioninfo: false
Download of https://julialangnightlies-s3.julialang.org/bin/mac/aarch64/julia-latest-mac64.tar.gz failed, trying again. Error: Error: Unexpected HTTP response: 404
```

That is, we are calling `julia-actions/setup-julia` with the input `arch: ARM64`, but `setup-julia` is trying the URL `https://julialangnightlies-s3.julialang.org/bin/mac/aarch64/julia-latest-mac64.tar.gz`.

I think this is a bug in `setup-julia`, but I'm not sure. @SaschaMann Any ideas?

Also cc: @staticfloat to take a look at the S3 download URL.

**Comment by DilumAluthge** [comment]
Just a quick aside about the `determine-julia-arch` stuff. That stuff is only necessary because we want some of our CI jobs to test 32-bit Julia.

If we only wanted to test on 64-bit Julia (whether x86_64 or aarch64), then we could get rid of all of the `determine-julia-arch` stuff, and we could just set the `arch` to `${{ runner.arch }}`, which GitHub Actions automatically sets to the correct value.

**Comment by ViralBShah** [comment]
https://github.com/julia-actions/setup-julia/pull/220 implements support for M1

**Comment by DilumAluthge** [comment]
Yeah, I'll update this branch once a new release is made upstream.

**Comment by DilumAluthge** [comment]
Looks like we're now downloading the correct aarch64 Julia. Huge thanks to @IanButterworth for cutting a new release of setup-julia.

@ViralBShah I need to clean up this PR quite a bit, but then we can merge it.

**Comment by ViralBShah** [comment]
I don't understand the PR. I thought OS should have mac/windows/linux, and arch should have x86, x64, aarch64, etc. But now, macos is in arch.

**Comment by ViralBShah** [comment]
@DilumAluthge Is this the final state of the CI file to commit? I think it has some experimentation code, that can perhaps be removed. Would be nice to get this merged.

**Comment by DilumAluthge** [comment]
A lot of the echos are just for debugging, and can likely be removed. But honestly we could merge this as is and clean it up later.

**Comment by ViralBShah** [comment]
Thanks @DilumAluthge. I was hoping that adding M1 runners would be simpler - like just adding a new arch or something to the matrix. I suppose as the M1 runner support matures in our infra, it will become easier, at which point I can add it to various other packages.

**Comment by IanButterworth** [comment]
@ViralBShah take a look at how Pkg did it https://github.com/JuliaLang/Pkg.jl/pull/3793

**Comment by ViralBShah** [comment]
> @ViralBShah take a look at how Pkg did it [JuliaLang/Pkg.jl#3793](https://github.com/JuliaLang/Pkg.jl/pull/3793)

Thanks - that was exactly what I was looking for.

**Pull request merged**
