### PR TITLE
Backports for Julia v1.8.x

### PR DESCRIPTION
**Pull request by Wimmerer**
Co-authored-by: Steven G. Johnson <stevenj@mit.edu>

Note: I want to be sure the attribution is correct here, I *think* it should say "authored by Jerry and Steven" and "committed by Wimmerer".

Backported PRs:

- [x] https://github.com/JuliaSparse/SparseArrays.jl/pull/93
- [x] https://github.com/JuliaSparse/SparseArrays.jl/pull/253
- [x] https://github.com/JuliaSparse/SparseArrays.jl/pull/260
- [x] https://github.com/JuliaSparse/SparseArrays.jl/pull/176

### CODE REVIEW

**Comment by dkarrasch** [comment]
x-ref #245 (I followed the instructions literally in the backport action error message, so it has slightly different source and target branches).

**Comment by Wimmerer** [comment]
Did that one pass tests? I'm not sure what the issue is with this one, maybe I didn't do it right. I just followed https://github.com/JuliaSparse/SparseArrays.jl/issues/249 without realizing you had already done the backport. We should collect #93 and #253 on a single `release-1.8` branch at some point before adjusting julialang/julia according to #249.

**Comment by KristofferC** [comment]
> Note: I want to be sure the attribution is correct here, I think it should say "authored by Jerry and Steven" and "committed by Wimmerer".

Do you do `git cherry-pick -x COMMIT`?

**Comment by Wimmerer** [comment]
Yes iirc

**Comment by Wimmerer** [comment]
@dkarrasch we just need the circshift changes here right? Then we're good to merge?

**Comment by dkarrasch** [comment]
It turns out we also have #176 labelled for backport.

**Comment by KristofferC** [comment]
Please push an update to https://github.com/JuliaLang/julia/pull/46663 when this is done.

**Comment by Wimmerer** [comment]
I only know how this works with BumpStdlibs.jl, is that used here?

**Comment by dkarrasch** [comment]
I guess now we should wait for the clean-up PR for circshift, right? Otherwise, I don't see anything on the horizon that needs action.

**Comment by Wimmerer** [comment]
circshift and I need to fix two typos I found. Then we're good.

**Comment by dkarrasch** [comment]
The release of v1.8.2 has been announced, and we really should get the backports in. Do we need to include anything else? Or shall we merge this and go ahead on the Julia Base side?

**Comment by Wimmerer** [comment]
I think this is ready to go @dkarrasch

**Comment by KristofferC** [comment]
I'm gonna merge this now so that it doesn't miss 1.8.3 as well.

**Pull request merged**
