### PR TITLE
fix a broken link in docs

### PR DESCRIPTION
**Pull request by ctarn**

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]

**Comment by fredrikekre** [comment]
Where do you see a broken link?

**Comment by ctarn** [comment]
should we use a more specific id instead? I am not so familiar with `Documentor.jl` and am worried that the docs of julia may have used the id, and may raise a conflict.

**Comment by fredrikekre** [comment]
Okay, looks like it has already been fixed in https://github.com/JuliaSparse/SparseArrays.jl/pull/430 so I think that PR should just be backported to 1.10

**Comment by ctarn** [comment]
Yes! It has been fixed in the docs of 1.12-dev. I am going to close the PR.
BTW, jump to `[#man-csc](https://docs.julialang.org/en/v1/stdlib/SparseArrays/#man-csc)` may be a bug of Documentor.jl. I noticed that you are a member of JuliaDocs, and maybe I don't have to create another issue in JuliaDocs :).
Thanks!

**Pull request closed without merging**
