### PR TITLE
Umfpack Thread safety fix

### PR DESCRIPTION
**Pull request by SobhanMP**
Is this what i was supposed to do? with some luck i managed to "transfer" the commits...

### CODE REVIEW

**Comment by SobhanMP** [comment]
@ViralBShah @Wimmerer

**Comment by SobhanMP** [comment]
hmmm

**Comment by SobhanMP** [comment]
btw, i still think that adding a lock would be a very good idea. it's not costly (at least not to anything we do with suitesparse).

**Comment by Wimmerer** [comment]
Okay you can go ahead and add

**Comment by SobhanMP** [comment]
i am somehow not running the tests locally correctly :/

**Comment by ViralBShah** [comment]
Seems like just not finding `@thread`: https://github.com/JuliaSparse/SparseArrays.jl/runs/6678759287?check_suite_focus=true#step:7:98

**Comment by SobhanMP** [comment]
no, i understand that. but why is `Pkg.test()`
 not giving me any errors?

**Comment by ViralBShah** [comment]
`Pkg.test("SparseArrays")` does not give an error on that?

**Comment by SobhanMP** [comment]
yeah, it's not running the tests locally for me. it skips umfpack

**Comment by SobhanMP** [comment]
ah, i forgot to change the hash...

**Comment by Wimmerer** [comment]
That always gets me, I just keep the hash changed and uncommitted.

**Comment by SobhanMP** [comment]
i guess that's it

**Comment by Wimmerer** [comment]
@SobhanMP I forgot the main problem with the lock. Right after this is merged I will move both the Control and Info structs into the `UmfpackLU` struct. `Info` is not thread safe, and I'm not sure it makes a ton of sense to have a lock on just the workspace anymore at that point since `Info` will also make it unsafe (and you don't want the `Info` structs to get clobbered).

We can extend what you had at one point, a function which created an aliased `UmfpackLU` but which allocated a new workspace to also allocate a new Info and Control.

Sorry about that.

**Comment by SobhanMP** [comment]
@Wimmerer ah, damn 

yeah give me an hour

**Comment by SobhanMP** [comment]
@Wimmerer welp that wasn't an hour, but i think this is what you meant, right?

**Comment by Wimmerer** [comment]
Exactly! Let me read it over locally and test and I'll go ahead and merge.

**Comment by SobhanMP** [comment]
btw will this go in 1.8?

**Comment by Wimmerer** [comment]
No. It'll go in 1.9, and actually SparseArrays will no longer be a standard library, just a plain old package at that point.

**Comment by SobhanMP** [comment]
i was looking forward to using this in stuff i'm working on...

**Comment by ViralBShah** [comment]
1.8 is already into RCs - this would have had to be in months ago by feature freeze. Going forward, with 1.9, if we successfully remove SparseArrays from the julia base distribution, then it will just be like any other package.

**Comment by SobhanMP** [comment]
i replaced the stdlib version in my installation and realized i had broken precompile

**Pull request merged**
