### PR TITLE
Add generic matmatmul for inplace sparse x sparse

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes https://github.com/JuliaLang/julia/issues/52429.

I have no idea which branches are really used and whether this can be further reduced, especially in favor of compile time, which was a big issue over at LinearAlgebra.jl. Currently, this is just a copy-paste from the old LinAlg code.

@dmbates @palday

### CODE REVIEW

**Comment by ViralBShah** [comment]
We should merge if ready - the windows issue is separate.

**Comment by palday** [comment]
can you point to commit + lines of the old LinearAlgebra code this is copied from?

**Comment by dkarrasch** [comment]
It's the one you found here: https://github.com/JuliaLang/julia/issues/52429#issuecomment-1847654946, i.e., https://github.com/JuliaLang/julia/commit/0cf2bf143552c2f425150fcb2a60225c67ea042d. It's in matmul.jl, lines 786ff.

**Comment by dkarrasch** [comment]
Shall we merge this? I believe there is room for further improvement by providing specialized ` copyto!` and `copy_transpose` methods, but I don't have the time to do that now.

**Comment by ViralBShah** [comment]
Agree - we should merge as is for now.

**Pull request merged**
