### PR TITLE
Enable julia stable in CI

### PR DESCRIPTION
**Pull request by ViralBShah**
Let's try to make sure we can keep this package going on Julia stable, and maybe even Julia 1.6.

@dkarrasch I believe the `Base.extremamap` is Julia 1.8 only (I believe it should have been added through your recent PR).  If possible, it would be nice to make the package in its current shape work on Julia 1.7, but if not, we can make 1.8 the minimum required going forward, but be more conservative going forward about using features in new Julia versions.

My purpose here is to just be a bit more deliberate.

### CODE REVIEW

**Comment by SobhanMP** [comment]
is there any reason? it's not like 1.6 is going to get a bumped version of this package.

**Comment by ViralBShah** [comment]
The main reason is not to backport or ship new SparseArrays with old releases, but to make sure that we don't break backwards compatibility accidentally. It's definitely a nice to have, among many of the other things that need doing here, rather than must have.

**Comment by Wimmerer** [comment]
It's important for people who depend on SparseArrays. If a new feature is added that doesn't support 1.6 it can become annoying for packages that *so* support 1.6

**Comment by SobhanMP** [comment]
i didn't know 1.6 still got SparseArrays updates.

**Comment by Wimmerer** [comment]
It doesn't. I was unclear.

**Comment by ViralBShah** [comment]
Right, only crucial bugfixes would get backported to lts and stable.

**Pull request merged**
