### PR TITLE
add allowscalar

### PR DESCRIPTION
**Pull request by SobhanMP**
closes https://github.com/JuliaSparse/SparseArrays.jl/issues/189

the only downside is that revise might act a bit weird. 

also maybe RCI should call `@eval` on `exp` direclty instead of returning `exp`?

another detail is that should this also block stuff like
```
A = sprandn(100, 100, 0.1)
A[i, :]
A[1:10, :]
```
or just the ones i marked?

This does NOT cause any degradation in any way, unlike adding a state variable.

### CODE REVIEW

**Comment by Wimmerer** [comment]
You mean it causes a 2% slow down?

**Comment by SobhanMP** [comment]
no it does not, Chris said that adding a flag for scalar (with a global `const scalar = Ref{Bool}(true)`) would cause a 2% slowdown. this does not do that.

**Comment by Wimmerer** [comment]
Are we doing both the static type and the macro?

**Comment by SobhanMP** [comment]
what static type?

**Comment by SobhanMP** [comment]
bump

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
I think the `allowscalar` API should be documented and marked experimental (and not exported).

**Pull request merged**
