### PR TITLE
Backports for Julia v1.10

### PR DESCRIPTION
**Pull request by dkarrasch**
#438

### CODE REVIEW

**Comment by dkarrasch** [comment]
@vtjnash Could you please review your recent cat-related commits and push those that are suitable for backport here?

**Comment by jishnub** [comment]
Can #423 be backported?

**Comment by ViralBShah** [comment]
Do we want to try to get these into Julia 1.10?

**Comment by dkarrasch** [comment]
Yes, definitely. We could merge now and then bump on Julia's release branch.

**Comment by dkarrasch** [comment]
In fact, how about backporting the docs commit? I think the changes there were (at the end) minimal and not version-dependent.

**Comment by ViralBShah** [comment]
One backport we should do is SuiteSparse 7.2.1. The current version on 1.10 uses @Wimmerer 's branch of SuiteSparse, but all that has been upstreamed in an official release in 7.2.1, which is making its way through Yggdrasil etc.

**Pull request merged**
