### PR TITLE
Update the wrappers for SuiteSparse 7 and remove `cholmod_blas.h` bindings

### PR DESCRIPTION
**Pull request by Gnimuc**
~~It looks like our old API in use is stable in SuiteSparse 7.~~

cc @ViralBShah

### CODE REVIEW

**Comment by ViralBShah** [comment]
There was a small API change that was implemented in https://github.com/JuliaSparse/SparseArrays.jl/commit/c09f0ac575165ddf4d264c15284d8fc0f8ac54b0

**Comment by ViralBShah** [comment]
Actually seems like it is not picking up the new SuiteSparse 7: https://github.com/JuliaSparse/SparseArrays.jl/blob/6a10bdabc8ba42df2aa501b5861be3baef572bab/src/solvers/lib/aarch64-apple-darwin20.jl#L2171

**Comment by ViralBShah** [comment]
I have updated `generator.jl` to work with this setup, but it generates wrappers that have things like `int64_t` and various other undefined things in them.

**Comment by Gnimuc** [comment]
I still get
```
ERROR: LoadError: Cannot locate artifact 'SuiteSparse' in '/Users/gnimuc/Code/juliasrc/usr/share/julia/stdlib/v1.10/SuiteSparse_jll/src/../Artifacts.toml'
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] ensure_artifact_installed(name::String, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, pkg_uuid::Nothing, verbose::Bool, quiet_download::Bool, io::Base.TTY)
   @ Pkg.Artifacts ~/Code/juliasrc/usr/share/julia/stdlib/v1.10/Pkg/src/Artifacts.jl:354
 [3] ensure_artifact_installed(name::String, artifacts_toml::String)
   @ Pkg.Artifacts ~/Code/juliasrc/usr/share/julia/stdlib/v1.10/Pkg/src/Artifacts.jl:346
 [4] top-level scope
   @ ~/.julia/dev/SparseArrays.jl/gen/generator.jl:12
in expression starting at /Users/gnimuc/.julia/dev/SparseArrays.jl/gen/generator.jl:12
```

We should doc how to develop and update a stdlib.

**Comment by Gnimuc** [comment]
> I am not checking in the generated files, since they do not work - but they are essentially what I had in #362.

It should be fine. I just checked the src of SuiteSparse:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/1d379153cd5f1ea5bc67d27dfaf5f018eb3038ad/CHOLMOD/Include/cholmod.h#L1017

these changes are intended.

**Comment by ViralBShah** [comment]
Do you get that error using my PR as well? I really hope we can make SparseArrays.jl a standalone package and not an stdlib.

cc @KristofferC

**Comment by ViralBShah** [comment]
@Gnimuc The problem with those generated files in #362 is that `int64_t` and some of those other things are not defined anywhere in the generated julia code. So they come up as undefined variables.

**Comment by Gnimuc** [comment]
> @Gnimuc The problem with those generated files in #362 is that `int64_t` and some of those other things are not defined anywhere in the generated julia code. So they come up as undefined variables.

Sorry. I finally understood the problem in https://github.com/JuliaSparse/SparseArrays.jl/pull/362#issuecomment-1464236676 . I thought there were something wrong when Clang.jl mistakenly translated those `Int64` types.

Those "constants" are used in macros, so we need to either ignore the macro identifier or manually add those definitions like what we have done here: https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/solvers/LibSuiteSparse.jl#L11

**Comment by Gnimuc** [comment]
To ignore a macro identifier, we can add it to this list: https://github.com/JuliaSparse/SparseArrays.jl/blob/main/gen/generator.toml#L9

For example, `__STDC_VERSION__` and `restrict` are being used in the definition of `SUITESPARSE_STDC_VERSION` and `SUITESPARSE_RESTRICT` respectively. 
```
const SUITESPARSE_STDC_VERSION = __STDC_VERSION__

const SUITESPARSE_RESTRICT = restrict
```

`SUITESPARSE_STDC_VERSION` and `SUITESPARSE_RESTRICT` should be added to the ignore list.

**Comment by Gnimuc** [comment]
> Do you get that error using my PR as well?

Yes. This is the full version info:

```
julia> versioninfo()
Julia Version 1.10.0-DEV.810
Commit 841e9df121 (2023-03-11 15:48 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.2.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, westmere)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

I remembered that in the old days, to develop a stdlib, one simple hack is to manually edit the UUID of that package. I believe this hack can not work with the latest master?

**Comment by ViralBShah** [comment]
> I remembered that in the old days, to develop a stdlib, one simple hack is to manually edit the UUID of that package. I believe this hack can not work with the latest master?

Yes, that's why I pinged @KristofferC here. I'm hoping that https://github.com/JuliaLang/julia/pull/48979 will merge soon, which will make this a lot easier, and the next step is to remove SparseArrays from the stdlibs altogether.

**Comment by fxcoudert** [comment]
Is there any news?

**Comment by fxcoudert** [comment]
Warning:

```
┌ Warning: CHOLMOD version incompatibility
│ 
│ Julia was compiled with CHOLMOD version 4.0.3. It is
│ currently linked with version 3.0.14.
│ This might cause Julia to terminate when working with
│ sparse matrix factorizations, e.g. solving systems of
│ equations with \.
│ 
│ It is recommended that you use Julia with the same major
│ version of CHOLMOD as the one used during the build, or
│ download the generic binaries from www.julialang.org,
│ which ship with the correct versions of all dependencies.
└ @ SparseArrays.CHOLMOD D:\a\SparseArrays.jl\SparseArrays.jl\src\solvers\cholmod.jl:199
```

and failure on 32-bit Windows.

**Comment by ViralBShah** [comment]
I wouldn't worry about the failures here, which are using the nightly built on julia master. If it works locally, I think we should merge it, and then bump on Julia master, with some tender love and care.

**Comment by Gnimuc** [comment]
I should point out that I didn't test it locally.

**Comment by ViralBShah** [comment]
I did run the SparseArrays tests on a build of Julia that pulls in SuiteSparse 7 and SparseArrays.jl from this PR. Everything works fine, except for a couple of QR factorization failures for `ordering=6`.

cc @Wimmerer

**Comment by ViralBShah** [comment]
The missing ordering above is added by enabling PARTITION (METIS) support in SuiteSparse. https://github.com/JuliaPackaging/Yggdrasil/pull/6445.

**Comment by ViralBShah** [comment]
@Gnimuc I think this doesn't treat the 32-bit OSes right.

https://buildkite.com/julialang/julia-master/builds/22268#018714ca-ee8c-4b4e-a2d6-9a1fa3c6c7b2

**Comment by ViralBShah** [comment]
The way to test is to use julia branch with [the SuiteSparse 7 PR](https://github.com/JuliaLang/julia/pull/48977) and update `SparseArrays.version` in `stdlib` to be the commit SHA of the commit in your branch/PR on this repo.

Since SparseArrays is no longer in the system image, you don't have to necessarily build Julia everytime you make a change.

**Comment by ViralBShah** [comment]
Trying in #372

**Comment by jvo203** [comment]
As per the comment below, this problem does not seem to have been fixed in the new Julia 1.9.0 yet. Is there any reasonable time estimate as to when this problem might be fixed?

https://github.com/JuliaLang/julia/pull/48977#issuecomment-1547111853

**Pull request merged**
