### PR TITLE
Break recursion

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by dkarrasch** [comment]
Is there a (simple) case that triggered indefinite recursion? Perhaps, we should add that as a test?

**Comment by wsmoses** [comment]
Extremely not reduced, but https://github.com/EnzymeAD/Enzyme.jl/issues/1134

The issue was introduced by https://github.com/JuliaSparse/SparseArrays.jl/commit/c402d09cf05492179fad2def5632e354a81f5b30

cc @gbaraldi and @vtjnash who discussed soltuions with me yesterday

**Comment by wsmoses** [comment]
ping for a review. @gbaraldi confirmed it fixes the issue at hand

**Comment by gbaraldi** [comment]
This also needs a backport to 1.11

**Comment by wsmoses** [comment]
and also to 1.10

**Comment by dkarrasch** [comment]
> This also needs a backport to 1.11

WIP [298f5e1](https://github.com/JuliaSparse/SparseArrays.jl/pull/571/commits/298f5e11d4b6bb7acd803780c5531e6c8eaa30e9)

**Comment by vtjnash** [comment]
> Is there a (simple) case that triggered indefinite recursion?

There never was any, but Enzyme modeled the previous code wrong, resulting in crashes there:
https://github.com/EnzymeAD/Enzyme.jl/issues/1134#issuecomment-1857584317

**Pull request merged**
