### PR TITLE
Disable Float16 approximate tests on Windows

### PR DESCRIPTION
**Pull request by ViralBShah**
Should help https://github.com/JuliaSparse/SparseArrays.jl/issues/147

Also only disables the Float16 tests on windows.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@Wimmerer Any idea what's going on with the docs?

**Comment by Wimmerer** [comment]
I have no idea. Why would docs take 22m?! I restarted that job.

**Comment by ViralBShah** [comment]
I had already restarted it and it failed the same way with the 404. And also failing in other PRs.

**Comment by Wimmerer** [comment]
I can build docs locally :/. This must be a CI thing?

**Comment by ViralBShah** [comment]
Definitely a CI thing, and pretty sure it is not because of our package. Hence merging things.

**Comment by ViralBShah** [comment]
Still failing on win64: https://build.julialang.org/#/builders/63/builds/6316/steps/5/logs/stdio

**Pull request merged**
