### PR TITLE
On the backports-v1.8 branch, run CI on v1.8

### PR DESCRIPTION
**Pull request by dkarrasch**
Maybe replaces #255?

### CODE REVIEW

**Comment by Wimmerer** [comment]
Should we open a PR to merge backports-release-1.8 => release-1.8 with this in it? That should trigger CI right?

**Comment by dkarrasch** [comment]
> backports-release-1.8 => release-1.8

Yes. We could do that right away, or include the vcat fix before that. But I guess the order doesn't matter much as long as we don't change the commit SHA in Julia `release-v1.8`, right?

**Comment by dkarrasch** [comment]
I'm merging this. It can't be wrong to do that IIUC.

**Comment by Wimmerer** [comment]
> change the commit SHA in Julia release-v1.8, right?

Yeah I say we merge into backports and just open a PR for CI purposes. Once we've done that and it passes we can follow up with Kristoffer or Dilum to be absolutely sure we've got it right.

**Pull request merged**
