### PR TITLE
Fix error message in getcommon() in cholmod

### PR DESCRIPTION
**Pull request by ViralBShah**
@rayegun I am not sure if this is right. I couldn't find `cholmod_common_l` anywhere.

### CODE REVIEW

**Comment by rayegun** [comment]
Yeah that's just to ensure they stay separated.

What was this PR for?

**Comment by ViralBShah** [comment]
I was looking for anything that might help resolve the threaded tests that fail in github actions. They don't fail on the julia buildbots but they always fail in github actions - and I was wondering if that was a real bug on our side. Specifically making sure that structs are correctly created and mirror what CHOLMOD expects (no overflows, etc.).

**Comment by rayegun** [comment]
Can you point me to the logs that fail?

**Comment by ViralBShah** [comment]
Yeah, see the failing windows tests in the CI right here in this PR. It times out in the threading tests.

**Pull request merged**
