### PR TITLE
Add Support for Single Precision

### PR DESCRIPTION
**Pull request by rayegun**
Incomplete, posting now for codecov purposes. There are some outstanding issues on how to do promotion and conversion, since the CHOLMOD built-in capabilities are limited.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Wow that is a huge PR!

**Comment by rayegun** [comment]
The vast majority of it is trying to handle promotion at least somewhat sanely. Since mixed precision is not supported (and probably never will be).

**Comment by rayegun** [comment]
Curses, I have no idea what's going on with Float32 on 32-bit plats. Are there arcane architectural differences afoot here? Or just a bad wrap somewhere :/

**Comment by rayegun** [comment]
This seems to be an artifact of using `sprand` here perhaps? Does that make sense to you @ViralBShah? I suppose it's possible that the matrix generated here is close to non-posdef, and that minor architectural changes are causing the issue?

If I run 
```julia
julia> Ftmp = SparseMatrixCSC{Float32, Int32}(sprandn(Tv, 100, 100, 0.1)); Ftmp = Ftmp'Ftmp + I;

julia> cholesky(Ftmp)
```
There's a 1 in 4 chance it fails, but not so with `Float64` on 32-bit Linux. This *never* occurs on 64 bit platforms, no matter which datatypes or index types are used.

**Comment by ViralBShah** [comment]
Just add a heavy diagonal:

`SparseMatrixCSC{Float32, Int32}(sprandn(Tv, 100, 100, 0.1)); Ftmp = Ftmp'Ftmp + 100*I`

Float32 can end up being non-posdef to numerical precision.

**Comment by ViralBShah** [comment]
There's a 20min timeout.

**Comment by ViralBShah** [comment]
Does the failing test on ComplexF32 suggest that there is a bug somewhere in the cholesky for single precision just added in the complex case?

**Comment by rayegun** [comment]
I need to trim the tests. I think I just located a bug in the wrapper, I'm running the tests on Ubuntu-32 right now. There was an assumption that only held for 64-bit case by accident.

**Comment by ViralBShah** [comment]
The tests are timing out on Windows after 6 hours. I have triggered the x64 test again. I believe it was going through successfully earlier in this PR, but perhaps the hanging is a sign of memory corruption.

**Comment by dkarrasch** [comment]
I think Windows tests have been hanging for a while, also in other PRs.

**Comment by rayegun** [comment]
The tests are currently massive for cholesky. I will work on reducing, we don't really need a complete product of Float32, Float64 x Real, Complex x Int32, Int64 for every test.

I just did that to naively check everything while making the changes

**Comment by ViralBShah** [comment]
The hangs since SuiteSparse 7.4 are a bit worrisome.

**Comment by rayegun** [comment]
Are those hangs really from SuiteSparse? The times for the SuiteSparse tests don't look that terrible. They're faster than my MacBook. Which definitely doesn't take 5 hours.

**Comment by rayegun** [comment]
Oh looks like indeed they happen after SuiteSparse 7.4 update. I wonder why 🤔  because the actual times don't look terrible.

**Comment by ViralBShah** [comment]
It's not straightforward to do this - but it would be great to have a PR for SuiteSparse 7.5 and see if that has the same issue.

**Comment by ViralBShah** [comment]
With #490 clearly identifying the issue on Windows, I think it is safe to merge this.

**Review by ViralBShah — APPROVED** [review]

**Pull request merged**
