### PR TITLE
test umfpack sanity

### PR DESCRIPTION
**Pull request by SobhanMP**
maybe this will help but it will make the tests take longer

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can we guard these with some debug flag, so that the flag can be set globally for debugging output? We can then temporarily enable it when we want to see more details.

**Comment by SobhanMP** [comment]
i'm not sure i understand how to do that, but since it's a function you can disable it see `umfpack_report` in the umfpack test. i can disable them there for now but i want to see the output of the CI

**Comment by SobhanMP** [comment]
it only takes 2 more minutes so maybe it's ok?

**Comment by ViralBShah** [comment]
Ok, let's go ahead and merge if ready. We should probably wait for the current stdlib bump to go through and see how it does before bumping again (maybe we can do another bump tomorrow or day after).

**Comment by SobhanMP** [comment]
how do you do that?

**Comment by ViralBShah** [comment]
I think it has to be done by someone with the permissions. But this will cancel the existing one. So let's wait for that to complete its CI, and then we trigger this one - probably tonight or tomorrow morning.

**Comment by SobhanMP** [comment]
will do :+1:

**Comment by ViralBShah** [comment]
These tests don't seem to pass locally for me.

```
➜  SparseArrays.jl git:(main) ~/julia/julia test/umfpack.jl 
Core functionality for Float64 elements: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:57
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{Float64, Int32}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{Float64, Int32})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:61 [inlined]
    [5] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1476 [inlined]
    [6] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:57 [inlined]
    [7] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [8] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
    [9] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [11] _start()
      @ Base ./client.jl:514
Core functionality for ComplexF64 elements: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:57
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{ComplexF64, Int32}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{ComplexF64, Int32})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:61 [inlined]
    [5] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1476 [inlined]
    [6] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:57 [inlined]
    [7] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [8] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
    [9] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [11] _start()
      @ Base ./client.jl:514
Allocations: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:95
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{ComplexF64, Int32}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{ComplexF64, Int32})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] (::Main.UMFPACKTests.var"#f#7"{Matrix{Float64}, Vector{Float64}, SparseArrays.SparseMatrixCSC{Float64, Int64}})(Tv::Type, Ti::Type)
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:83
    [5] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:98 [inlined]
    [6] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [7] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:96 [inlined]
    [8] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [9] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
   [10] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [11] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [12] _start()
      @ Base ./client.jl:514
Thread safety: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:103
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:105 [inlined]
    [5] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [6] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:104 [inlined]
    [7] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [8] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
    [9] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [11] _start()
      @ Base ./client.jl:514
test similar: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:123
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:125 [inlined]
    [5] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [6] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:124 [inlined]
    [7] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [8] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
    [9] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [11] _start()
      @ Base ./client.jl:514
test duplicate: Error During Test at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:134
  Got exception outside of a @test
  BoundsError: attempt to access 20-element Vector{Float64} at index [0]
  Stacktrace:
    [1] getindex
      @ ./essentials.jl:13 [inlined]
    [2] umfpack_report_numeric(lu::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64}, level::Int64)
      @ SparseArrays.UMFPACK ~/julia/usr/share/julia/stdlib/v1.9/SparseArrays/src/solvers/umfpack.jl:925
    [3] umfpack_report(l::SparseArrays.UMFPACK.UmfpackLU{Float64, Int64})
      @ Main.UMFPACKTests ~/repos/SparseArrays.jl/test/umfpack.jl:14
    [4] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:136 [inlined]
    [5] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [6] macro expansion
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:135 [inlined]
    [7] macro expansion
      @ ~/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:1388 [inlined]
    [8] top-level scope
      @ ~/repos/SparseArrays.jl/test/umfpack.jl:54
    [9] include(mod::Module, _path::String)
      @ Base ./Base.jl:424
   [10] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:299
   [11] _start()
      @ Base ./client.jl:514
Test Summary:                                | Error  Total  Time
Workspace management                         |     6      6  4.8s
  Core functionality for Float64 elements    |     1      1  2.4s
  Core functionality for ComplexF64 elements |     1      1  0.8s
  Allocations                                |     1      1  0.1s
  Thread safety                              |     1      1  0.3s
  test similar                               |     1      1  0.0s
  test duplicate                             |     1      1  0.0s
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 6 errored, 0 broken.
in expression starting at /Users/viral/repos/SparseArrays.jl/test/umfpack.jl:3
```

**Pull request merged**
