### PR TITLE
Don't materialize when adding/subtracting an `Array`

### PR DESCRIPTION
**Pull request by jishnub**
This improves performance and reduces allocation:
```julia
julia> S = sprand(1000, 1000, 0.04);

julia> @btime $S + $(Array(S));
  2.107 ms (4 allocations: 15.26 MiB) # main
  1.539 ms (2 allocations: 7.63 MiB) # PR
```

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]

**Comment by ViralBShah** [comment]
Would this be considered a breaking change? I suspect it could change the behaviour of many things in the package ecosystem.

**Comment by jishnub** [comment]
I'm afraid I don't know enough to comment, but wouldn't this work as long as subtypes of `AbstractSparseMatrixCSC` implement `rowvals`, `nonzeros` and `nzrange`? The result is materialized in either case.

**Comment by dkarrasch** [comment]
I agree with @jishnub: I don't see how this would be breaking. It uses what seems to be the "interface" of `AbstractSparseMatrixCSC`, and the methods are designed for Base's `Array`s, so that shouldn't interfere with other array types from the ecosystem. Finally, the return type is `Matrix`, so again nothing generic.

**Comment by ViralBShah** [comment]
I suppose breaking is not the right word - but perhaps the issue is that people may be relying on this behaviour and performance characteristics may change in their codes.

I am ok with merging this - just wanted to raise the issue for discussion.

**Comment by SobhanMP** [comment]
Can you benchmark it when the array is almost full (`sprand(1000, 1000, 0.99)`)?
What does the `Ref` in `C = Ref(zero(eltype(A))) .+ B` do? 
p.s.
Nice observation!

**Comment by jishnub** [comment]
To answer the Ref point: this ensures that the zero element is treated as a scalar and added elementwise to the `Array`, even when it is an array itself.

**Comment by jishnub** [comment]
Using a highly filled array:
```julia
julia> S = sprand(1000, 1000, 0.99);

julia> @btime $S + $(Array(S));
  3.347 ms (4 allocations: 15.26 MiB) # main
  2.912 ms (2 allocations: 7.63 MiB) # PR
```

**Comment by ViralBShah** [comment]
The perf concern is not with the implementation here, but that returning a different matrix type will have potential performance impact on code that use the results of these operations.

**Comment by dkarrasch** [comment]
We are not returning a different matrix type, we return the same matrix type as before. Users won't see any difference except for better performance.

**Comment by ViralBShah** [comment]
> We are not returning a different matrix type, we return the same matrix type as before. Users won't see any difference except for better performance.

Oops never mind.

**Comment by SobhanMP** [comment]
@jishnub Thanks for the benchmarks and the explanation!

**Pull request merged**
